[default]
check-filename = true

[files]
extend-exclude = [
    "node_modules",
    "android",
    "*.css",
    "*.gradle",
    "capacitor.config.ts",
]

[default.extend-words]
strech = "strech"
contaienr = "contaienr"
formate = "formate"
collapsable = "collapsable"
styl = "styl"
