[default]
check-filename = true

[files]
extend-exclude = [
  "node_modules",
  "android"
]

[default.extend-words]
strech = "strech"
contaienr = "contaienr"
collapsable = "collapsable"
styl = "styl"
