[default]
check-filename = true

[files]
extend-exclude = [
  "www/src/js/modules",
  "www/src/locales/lang",
  "node_modules",
  "ios",
  "android",
  "socket"
]

[default.extend-words]
strech = "strech"
contaienr = "contaienr"
collapsable = "collapsable"
styl = "styl"
